lib/WTSI/NPG/Accountable.pm, lib/WTSI/NPG/Annotatable.pm, lib/WTSI/NPG/Annotation.pm, lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/ACLModifier.pm, lib/WTSI/NPG/iRODS/Collection.pm, lib/WTSI/NPG/iRODS/Communicator.pm, lib/WTSI/NPG/iRODS/DataObject.pm, lib/WTSI/NPG/iRODS/DataObjectReader.pm, lib/WTSI/NPG/iRODS/GroupAdmin.pm, lib/WTSI/NPG/iRODS/Lister.pm, lib/WTSI/NPG/iRODS/MetaLister.pm, lib/WTSI/NPG/iRODS/MetaModifier.pm, lib/WTSI/NPG/iRODS/MetaSearcher.pm, lib/WTSI/NPG/iRODS/Path.pm, lib/WTSI/NPG/iRODS/Storable.pm, lib/WTSI/NPG/iRODS/Version.pm
This ensures that there is sufficient metadata to identify the file contents when working with a
batch of data objects returned from another query.
=> Return AVUs when reading data objects.

.travis.yml, lib/WTSI/NPG/Accountable.pm
Update baton and Jansson versions, install more recent Perl URI module.
Replace use of whoami with Perl builtin.
=> Final changes for 1.5.1. release

bin/populate_wtsi_irods_groups.pl
Do two getent calls (passwd and group) instead of one for each required group and take note of users primary group as well as secondary group membership.
If the data access group contains a string we do not recognise as a group then try treating it as an individual user.
=> Use unix primary group membership and allow individual users in data access group

lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/Collection.pm, lib/WTSI/NPG/iRODS/Lister.pm, lib/WTSI/NPG/iRODS/MetaSearcher.pm, t/lib/WTSI/NPG/iRODSTest.pm
This commit fixes two bugs:
It was impossible to search with metadata AVUs where any part was Perl
zero (int or string). This was caused by overzealous argument checking.
Using a single lister for paths, ACLs, checksums and collection
contents caused a performance bottleneck due to unnecessary ACL
lookups. Separate listers have been added for ACLs and collection
contents.
=> Argument check fix, performance fix

lib/WTSI/NPG/iRODS/Collection.pm, lib/WTSI/NPG/iRODS/DataObject.pm, lib/WTSI/NPG/iRODS/Path.pm
Use builders to lazily load data from iRODS, rather than 'around' method modifiers.
Fixed a documentation typo and added some documentation and comments.
=> Use builders to lazily load data from iRODS

lib/WTSI/NPG/iRODS/Path.pm, lib/WTSI/NPG/iRODS/Utilities.pm, t/lib/WTSI/NPG/iRODSTest.pm
Removed the "around" method on metadata because the underlying WTSI::NPG::iRODS metadata fetch method now sorts the AVUs, making this redundant.
Avoid creating unnecessary {units => undef} pairs in AVUs. The convention is that if units are not present, we don't include the key.
=> Avoid creating unnecessary {units => undef} pairs in AVUs

t/lib/WTSI/NPG/DriRODSTest.pm, t/lib/WTSI/NPG/iRODS/CollectionTest.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm, t/lib/WTSI/NPG/iRODS/PerformanceTest.pm, t/lib/WTSI/NPG/iRODSTest.pm
Only enable any group tests if all test groups are present.
Only try DriRODS group removal tests as an admin who can remove
groups.
=> Improvements to tests relating to iRODS groups

.travis.yml, Changes, MANIFEST, t/drirods.t, t/irods.t, t/irods_collection_test.t, t/irods_dataobject_test.t, t/lib/WTSI/NPG/DriRODSTest.pm, t/lib/WTSI/NPG/iRODS/CollectionTest.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm, t/lib/WTSI/NPG/iRODS/PerformanceTest.pm, t/lib/WTSI/NPG/iRODS/Test.pm, t/lib/WTSI/NPG/iRODSTest.pm, t/performance.t
Added test base class to handle setting irodsEnvFile environment variable.
Removed Test::More plan test counts because they can
calculated. Removed use_ok tests in BEGIN blocks because they cannot
be counted automatically and 'use' failures are evident anyway when
they occur.
=> Added test base class to handle setting irodsEnvFile environment

lib/WTSI/NPG/iRODS/Utilities.pm
Avoid implicit hash dereference when using keys builtin on a hashref.
Use strict/warnings are redundant when using Moose.
=> Avoid implicit hash dereference when using keys builtin on a hashref.

lib/WTSI/NPG/iRODS.pm, t/lib/WTSI/NPG/iRODSTest.pm
baton 0.16.2 is a release that fixes a bug wtsi-npg/baton/issues/140 for HGI
=> Support baton 0.16.2

lib/WTSI/NPG/DriRODS.pm, lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/ACLModifier.pm, lib/WTSI/NPG/iRODS/Collection.pm, lib/WTSI/NPG/iRODS/DataObject.pm, t/lib/WTSI/NPG/iRODS/CollectionTest.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm, t/lib/WTSI/NPG/iRODSTest.pm
The zone given in using this syntax will be honoured only with baton >= 0.16.3. With older
versions, the zone component will be ignored.
=> Permit user#zone syntax for users and groups

.travis.yml, lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/Communicator.pm, t/lib/WTSI/NPG/iRODSTest.pm
We need baton >= 0.16.4 in order to muffle these errors safely.
=> Muffle expected errors from the lister client.

bin/miget.pl, bin/populate_wtsi_irods_groups.pl, etc/log4perl_tests.conf, lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/DataObject.pm, lib/WTSI/NPG/iRODS/Path.pm, lib/WTSI/NPG/iRODS/Utilities.pm
The two production scripts now use Log4perl easy_init by default. I've tested these to see that the
logging behaviour is unchanged from the current release.
=> Switch to logging on a per-class basis.

.travis.yml
The workaround for shortening the hostname in Travis no longer works and stops Postgres from resolving localhost. Builds now work without it, but fail if it remains.
=> The workaround for shortening the hostname in Travis no longer works

Build.PL, bin/populate_wtsi_irods_groups.pl
=> Use ML warehouse

lib/WTSI/NPG/iRODS.pm, t/lib/WTSI/NPG/iRODSTest.pm
The use of `catfile` from `File::Spec::Functions` prompted me to change `File::Spec` to  `File::Spec::Functions` throughout, for consistency. (`File::Spec::Functions` is used in all the new code.)
=> Fix for staging iput where the target path is a collection

bin/populate_wtsi_irods_groups.pl
Added an undef check for cases where a user's gidNumber doesn't have a corresponding Unix group.
=> Check for cases where a user's gidNumber doesn't have a group

lib/WTSI/NPG/iRODS/Annotator.pm, t/lib/WTSI/NPG/iRODS/AnnotatorTest.pm
Archive suffixes are recognised. Custom suffixes no longer replace defaults.
=> Improved the handling of file suffix metadata

lib/WTSI/NPG/iRODS/Publisher.pm
Made the irods handle attribute lazy to avoid immediate calls to baton when a Publisher is created.
=> Made the Publisher irods handle attribute lazy

MANIFEST, scripts/travis_script.sh, t/lib/WTSI/NPG/iRODS/ReporterTest.pm, t/lib/WTSI/NPG/iRODS/TestRabbitMQ.pm
Run full tests (requiring a test RabbitMQ server) only if specified by environment variables:
* If TEST_RABBITMQ is set to a false value, skip RabbitMQ tests.
* If TEST_RABBITMQ is not set, fall back to TEST_AUTHOR. Run RabbitMQ tests if TEST_AUTHOR is true; skip tests if it is false or undefined.
Typical use case: TEST_AUTHOR is true, to enable tests using iRODS. Then default behaviour is to run RabbitMQ tests as well, unless explicitly cancelled by setting TEST_RABBITMQ to false.
=> Toggle RabbitMQ tests with environment variables

lib/WTSI/NPG/iRODS.pm
Arguments to ensure_object_path and ensure_collection_path must be defined and non-empty.
=> Check on ensure object/collection path arguments

lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/BatonClient.pm
Disabled staging/unstaging data objects to work around a baton bug in the function to move/rename objects
(https://github.com/wtsi-npg/baton/issues/189). Thhis also removes the complexity of staging and unstaging data objects which provided little benefit in practice.
=> Disabled staging/unstaging data objects to work around a baton bug

lib/WTSI/NPG/iRODS/Reportable.pm, scripts/rabbitmq_config.pl, t/lib/WTSI/NPG/RabbitMQ/TestCommunicator.pm, t/lib/WTSI/NPG/iRODS/ReporterTest.pm
- Bugfix: Change default routing key to match pattern in Travis test config
- Declare a separate RabbitMQ channel for each test
- Rename TestSubscriber as TestCommunicator and add a 'publish' method
- Add a 'sanity check' test of TestCommunicator and message queue to ReporterTest.pm
- If no message is read from the test queue, skip subsequent tests
=> Additional tests, bugfix and comments for RabbitMQ

t/lib/WTSI/NPG/iRODS/ReporterTest.pm, t/lib/WTSI/NPG/iRODS/TestRabbitMQ.pm
Packages depend on Net::AMQP::RabbitMQ:
- WTSI::NPG::iRODSMQTest
- WTSI::NPG::PublisherMQTest
- WTSI::NPG::RabbitMQ::TestCommunicator
The 'use' statements in WTSI/NPG/iRODS/ReporterTest.pm imported these packages even when RabbitMQ tests were being skipped. This cased an error when Net::AMQP::RabbitMQ was not installed. Instead, 'require' statements have been put in WTSI/NPG/iRODS/TestRabbitMQ.pm, so the packages are only imported if they are actually going to be used.
=> Move 'use' statements into TestRabbitMQ

Changes, lib/WTSI/NPG/iRODS/Publisher.pm, t/data/publisher/publish_file/d.txt, t/lib/WTSI/NPG/iRODS/PublisherTest.pm
Allow publishing from read-only directories by reducing the severity of failure to create MD5 cache files from a hard error to a warning.
Reduced log level of creating missing MD5 cache files from warning to debug.
=> Allow publishing from read-only directories by reducing the severity

lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/BatonClient.pm, lib/WTSI/NPG/iRODS/Collection.pm, t/lib/WTSI/NPG/iRODS/CollectionTest.pm
Fixed a long-standing bug in Collection.pm where using the checksum argument resulted in a null dereference.
Added POD and tests.
=> Fixed null dereference in Collection::collection_checksums

lib/WTSI/NPG/iRODS/BatonClient.pm, t/lib/WTSI/NPG/iRODSTest.pm
The bug fix itself is passing the correct option to baton v 2.0.0, 'checksum' instead of 'calculate_checksum'. The options is now always passed, i.e. the Perl wrapper does not rely on baton's default behaviour in respect of server-side calculation of checksums.
It seems that when not checksum is associated with an object, an undefined value is now returned rather than an empty string; this is reflected in the tests.
Blocks of tests that examined checksums and previously marked marked as TODO are now passing.
=> checksum bug fix in put_object method

Changes, lib/WTSI/NPG/iRODS/Metadata.pm
Take advantage of 1 year hiatus to rename gbs_plex (used within NPG genotyping by sequencing flow) to primer_panel so the iRODS meta data field will be consistent with the field name PSD chose to use in the iseq_flowcell table in the mlwarehouse.
=> Change gbs_plex to primer_panel in Metadata

Build.PL, bin/miget.pl, lib/WTSI/NPG/iRODS.pm, lib/WTSI/NPG/iRODS/Annotator.pm, lib/WTSI/NPG/iRODS/DataObject.pm, lib/WTSI/NPG/iRODS/GroupAdmin.pm, lib/WTSI/NPG/iRODS/Path.pm, lib/WTSI/NPG/iRODS/Publisher.pm, lib/WTSI/NPG/iRODS/Utilities.pm, t/lib/WTSI/NPG/DriRODSTest.pm, t/lib/WTSI/NPG/iRODS/CollectionTest.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm, t/lib/WTSI/NPG/iRODS/PerformanceTest.pm, t/lib/WTSI/NPG/iRODSTest.pm
List::AllUtils exposes functions from List::Util in preference to any
others. We were using a 'zip' function exposed by List::AllUtils that
was not from List::Util, which accepted two arrays.
List::Util 1.56 has added a 'zip' function which accepts two
arrayrefs, which is now exposed by List::AllUtils instead of the
previously exposed implementation.
This change caused our make_avus_from_objects method to fail (this is
used in one place in npg_irods). This change uses List::MoreUtils
'zip' implementation explicitly.
=> Switch from List::AllUtils to List::MoreUtils implementation of 'zip'

.github/workflows/run-tests.yml, scripts/install_wsi_dependencies.sh
We want to cache the CPAN modules, but not the NPG modules.
Remove some redundant operations on local::lib.
=> Install NPG Perl modules separately from CPAN modules to avoid caching

.github/workflows/run-tests.yml
Remove conda-forge from Conda channels as it is not required for any
dependencies of baton 3.0.0.
Depends on https://github.com/wtsi-npg/npg_conda/pull/253
=> Add baton 3.0.0, remove baton 2.1.0

MANIFEST, bin/npg_copy_collection.pl, bin/npg_move_collection.pl, lib/WTSI/NPG/iRODS.pm, t/lib/WTSI/NPG/iRODSTest.pm, t/perlcriticrc
Add a copy_collection method.
Refactor a common copying method.
Add utility scripts to copy and move collections, including all
metadata on the collections and contained data objects.
=> Add deep collection copy and move utility scripts

lib/WTSI/NPG/iRODS.pm
One line change: The aim is to remove -T option from icommand calls because it may cause the connection to freeze after 10 minute when the collection retrieval hangs, with a cliReconnManager: Reconnecting clientState = 0 message.
=> Remove -T option from icommands execution

lib/WTSI/NPG/iRODS.pm, t/lib/WTSI/NPG/iRODSTest.pm
The branch updates the get_object function. This fix allows get_object to resolve relative paths. Fix for issue #224.
=> Allow local paths to be resolved by get_object

t/lib/WTSI/NPG/iRODS/GroupAdminTest.pm
The test failed when using Docker/Singularity wrappers because although the test outcome is correct (the constructor raises an error), the error message string did not match the expected pattern.
The error message differs between macOS and Linux and between Singularity and Docker. It also depends on the shell environment.
This changes the test to simply test for failure when a failure condition is set up.
=> Fix failure due to a fragile test

.github/workflows/run-tests.yml, t/lib/WTSI/NPG/iRODS/GroupAdminTest.pm, t/lib/WTSI/NPG/iRODSTest.pm
Remove the combination of 4.2.11 clients with a 4.2.7 server
Add the combination of 4.2.7 clients with a 4.2.7 server Add the combination of 4.3-nightly clients with a 4.3-nightly server
=> Update test matrix iRODS versions

lib/WTSI/NPG/iRODS/DataObject.pm, lib/WTSI/NPG/iRODS/Path.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
Consolidated all logic about study-related ACLs.
Consolidated all logic about study-related ACLs
in the expected_groups method of WTSI::NPG::iRODS::Path thus
making this part of logic independent of the sequencing platform.
In future this logic can be applied, if necessary, to iRODS
collections.
Elements of this logic are moved from WTSI::NPG::iRODS::DataObject.
The logic related to xahuman is currently inplemented in npg_irods
GitHub package.
Built on top of https://github.com/wtsi-npg/perl-irods-wrap/pull/296, but can be considered as self-contained on its own merits
Should be followed by https://github.com/wtsi-npg/npg_irods/pull/439
=> Consolidate acl rules

lib/WTSI/NPG/iRODS/Path.pm, t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
Previously no end-user access was provided to
unconcented human split-out data. For each study a new iRODS group will be created. This pull request enables access to the nonconcented human data via this new group.
=> Provided access to human split-out data.

lib/WTSI/NPG/iRODS/Publisher.pm
When a data object is overwritten, the publisher currently assumes that only the object's data needs updating and does not check core metadata. This can leave objects without md5 or type metadata if their initial upload didn't didn't complete correctly.
This change adds some metadata updates that will be redundant in most cases, but will catch those cases.
=> Fix publisher to be better at metadata consistency
