- .travis.yml
- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/Collection.pm
- lib/WTSI/NPG/iRODS/Communicator.pm
- lib/WTSI/NPG/iRODS/DataObject.pm
- lib/WTSI/NPG/iRODS/Lister.pm
- t/lib/WTSI/NPG/iRODS/CollectionTest.pm
- t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Added checksum reporting.
Added zone to permissions return values.
Require baton 0.15.0.
> Added checksum reporting.

- lib/WTSI/NPG/iRODS/DataObject.pm
- t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
Changed the behaviour of WTSI::NPG::iRODS::DataObject::update_group_permissions
to be tolerant of unknown iRODS groups by default.
> Tolerant update_group_permissions

- etc/log4perl_tests.conf
- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/Communicator.pm
- lib/WTSI/NPG/iRODS/Lister.pm
- lib/WTSI/NPG/iRODS/MetaLister.pm
- lib/WTSI/NPG/iRODS/MetaModifier.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Added WTSI::NPG::iRODS::is_collection and WTSI::NPG::iRODS::is_object methods to allow improvements to argument checking.
> Improved object vs. collection path argument checks

- t/irods.t
- t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
- t/lib/WTSI/NPG/iRODS/PerformanceTest.pm
Limited the performance tests to be run only on selected iRODS zones.
Made the performance limits more lenient.
> Limited the performance tests to be run only on selected iRODS zones.

- lib/WTSI/NPG/iRODS.pm
> Corrected POD for method return values.

- lib/WTSI/NPG/iRODS/Metadata.pm
- lib/WTSI/NPG/iRODS/Types.pm
> Added more metadata keys and updated the Moose types to include

- lib/WTSI/NPG/iRODS.pm
Added a destructor to make the iRODS handle responsible for stopping its baton clients. This allows it to capture the results in its log.
> Handle client shutdown in the iRODS destructor

- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/Utilities.pm
Added ACL caching.
Renamed some attributes to indicate "privacy".
> Added ACL caching.

- lib/WTSI/NPG/iRODS.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Added a method parameter to allow server-side checksum calculation to be deferred when adding or replacing data objects.
> Added a method parameter to checksum calculation

- bin/populate_wtsi_irods_groups.pl
Use ou=people,dc=sanger,dc=ac,dc=uk to query users
Do not restrict the query to real people
> LDAP User query bug fix

- scripts/travis_before_install.sh
- scripts/travis_install.sh
- scripts/travis_script.sh
Added -u to require initialised variables. Fixed uninitialised variables.
> Run scripts under -u

- t/lib/WTSI/NPG/DriRODSTest.pm
- t/lib/WTSI/NPG/iRODS/CollectionTest.pm
- t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
- t/lib/WTSI/NPG/iRODS/GroupAdminTest.pm
- t/lib/WTSI/NPG/iRODS/PerformanceTest.pm
- t/lib/WTSI/NPG/iRODS/Test.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Also refactored to get all this in one place
> Clean up groups after test

- bin/populate_wtsi_irods_groups.pl
> speedup (using hash instead of RE in loop) of id to iRODS user(s)

- .travis.yml
- Build.PL
- MANIFEST
- README
- lib/WTSI/NPG/RabbitMQ/Connectable.pm
- lib/WTSI/NPG/iRODS.pm
- scripts/travis_install.sh
- scripts/travis_script.sh
- t/lib/WTSI/NPG/RabbitMQ/TestSubscriber.pm
- t/lib/WTSI/NPG/TestMQiRODS.pm
- t/lib/WTSI/NPG/iRODS/ReporterTest.pm
- t/lib/WTSI/NPG/iRODS/TestRabbitMQ.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Bumped baton version to 1.0.0
Avoid loading Net::AMQP::RabbitMQ in tests when not testing RabbitMQ support
Updated MANIFEST
> Pre release tweaks

- lib/WTSI/NPG/iRODS.pm
This patch changes two behaviours when (un)staging new data objects, Firstly, any error on staging or unstaging will result in the staged object being deleted, rather than being tagged for inspection. Secondly, the staging=1 AVU is handled such that when a failure leaves it in place on the final data object, any subsequent re-publishing will ignore it, rather than raise an error.
> Make staging of data objects idempotent on iRODS failures

- lib/WTSI/NPG/iRODS.pm
merge devel to master for release 3.0.1
> release 3.0.1 prep

- .travis.yml
- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/Annotator.pm
- t/lib/WTSI/NPG/iRODSTest.pm
> merge devel to master

- lib/WTSI/NPG/iRODS/Metadata.pm
> Added a COMPONENT to the standard metadata.

- Changes
- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/BatonClient.pm
- lib/WTSI/NPG/iRODS/Collection.pm
- t/lib/WTSI/NPG/iRODS/CollectionTest.pm
> prep for release 3.5.1

- lib/WTSI/NPG/iRODS/Annotator.pm
Add my stuff to another location.
> Add bqsr_table to annotator

- Changes
- lib/WTSI/NPG/iRODS.pm
Alternative to, and closes #197
> irods_major_version removed: support for iRODS 3 dropped, cope with 4.2

- .travis.yml
- lib/WTSI/NPG/iRODS.pm
- scripts/travis_install.sh
- t/lib/WTSI/NPG/iRODSTest.pm
Test using new iRODS 4.2.7 clients.
Fix data object replacement checksum behaviour in line with test.
WTSI to WSI to update for Institute rebranding.
> Feature/test irods 4.2.7 clients

- .travis.yml
- Changes
Remove iRODS 4.1.12
Add iRODS 4.2.8
> Update test iRODS version

- Changes
- lib/WTSI/NPG/iRODS/Publisher.pm
- t/lib/WTSI/NPG/iRODS/PublisherTest.pm
- Test for presence of checksum, and calculate it if it doesn't exist
> Improve reupload behaviour to handle the remote file missing its checksum

- .travis.yml
The YAML conformed to Travis CI docs example, but actually didn't work. This is an alternative way of expressing the same config
> Fix build matrix for iRODS 4.2.8

- Build.PL
- README
- lib/WTSI/NPG/iRODS.pm
- scripts/travis_install.sh
- scripts/travis_script.sh
- t/lib/WTSI/NPG/iRODS/Test.pm
Remove RabbitMQ.
Remove iRODS 4.1.*.
> Remove deprecated technologies

- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/BatonClient.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Add remove_collection_safely method which will only remove collections
that are empty, or themselves contain only empty collections.
`imv` fails to move cleanly collections that contain other collections and/or data objects.
This change works around that bug by re-implementing `imv` for collections using
copying of collections, `imv` of data objects and safe recursive removal of the original
collection.
> Add move_collection workaround for bug in imv

- .github/workflows/run-tests.yml
- lib/WTSI/NPG/iRODS.pm
Add baton 3.0.1
Remove conda-forge channel
> Update the baton iRODS client to test on upcoming iRODS versions

- lib/WTSI/NPG/iRODS.pm
- lib/WTSI/NPG/iRODS/BatonClient.pm
Typo in target Collection constructor arguments.
Add explanatory comments.
> Fix WTSI::NPG::iRODS::_copy_collection

- .github/workflows/run-tests.yml
- Changes
pull from devel to master to create Release 3.17.1
> pull from devel to master to create Release 3.17.1

- bin/populate_wtsi_irods_groups.pl
Clarify the policy on handling default membership for iRODS groups.
> Update iRODS permissions policy documentation

- .github/workflows/run-tests.yml
- t/lib/WTSI/NPG/DriRODSTest.pm
- t/lib/WTSI/NPG/iRODS/CollectionTest.pm
- t/lib/WTSI/NPG/iRODS/DataObjectTest.pm
- t/lib/WTSI/NPG/iRODS/GroupAdminTest.pm
- t/lib/WTSI/NPG/iRODS/PerformanceTest.pm
- t/lib/WTSI/NPG/iRODS/PublisherTest.pm
- t/lib/WTSI/NPG/iRODSTest.pm
Add Singularity installation, configuration.
Add a caching step for Singularity images.
Remove use of Conda-based iRODS clients.
Remove use of Conda-based Python.
> Add Singularity container support for iRODS clients

- .github/workflows/run-tests.yml
instead of workspace/ repo checkout dir.
c.f. https://github.com/wtsi-npg/npg_irods/pull/431
> GHA: move irods client deployment and singularity cache to HOME

- Changes
- bin/populate_wtsi_irods_groups.pl
Needs https://github.com/wtsi-npg/ml_warehouse/pull/234
https://jira.sanger.ac.uk/browse/NPG-2139
> Contaminated human data access group
